### PR TITLE
Add 'fetch' based methods for first() and find()...

### PR DESCRIPTION
**Pull request by leeovery**
Add 'fetch' based for first() and find() to enable single object responses with 'data' wrapper attribute present.

### CODE REVIEW

**Comment by robsontenorio** [comment]
Nice job! I will review it. Can you help me with #56?

**Comment by leeovery** [comment]
@robsontenorio Sure Ill try take a look tonight if I can :)

**Comment by DanWithams7d** [comment]
Implementation looks good to me, will be using @leeovery 's branch until @robsontenorio accepts this PR.

**Comment by rossity** [comment]
I believe this makes calls such as `save()` fail, as `save()` only works when calling `find()`, not `$find()`

Otherwise you get `save() is not a function`

**Comment by rossity** [comment]
Edit, I submitted a PR to fix this issue here https://github.com/robsontenorio/vue-api-query/pull/67

**Pull request merged**
