### PR TITLE
feat(model): add support to nested keys for relations

### PR DESCRIPTION
**Pull request by JoaoPedroAS51**
As requested by @francoism90, this PR add support for nested keys e.g. `relationships.tags`

### Usage
You can apply a model instance to a nested object by setting the key and the model in `relations` method.

If the backend responds with:
```js
// response from API for /posts/1
{
  title: 'My title'
  body: 'Some text here',
  relationships: {
    tags: [
      {
        name: 'super'
      },
      {
        name: 'awesome'
      }
    ]
  }
}
```

We just need to set `relationships.tags` to Tag model:

**/models/Post.js**
```js
class Post extends Model {
  relations () {
    return {
      // Apply Tag model to each object of `relationships.tags` array
      'relationships.tags': Tag
    }
  }
}
```

### CODE REVIEW

**Comment by francoism90** [comment]
@JoaoPedroAS51 Many thanks 👍

**Comment by robsontenorio** [comment]
@JoaoPedroAS51 muito bom! Você poderia me mandar um DM @robsontenorio no Twitter?

**Comment by JoaoPedroAS51** [comment]
@robsontenorio Eu não uso o Twitter. Pode ser Discord? Joao Pedro AS51#1284

**Comment by francoism90** [comment]
@robsontenorio Sorry for asking, but is this going to be merged/planned to be supported? :)

**Comment by JoaoPedroAS51** [comment]
@francoism90 Yes, it will be merged soon. :)

**Comment by francoism90** [comment]
@robsontenorio @JoaoPedroAS51 It seems this is missing in the docs? :)

**Comment by JoaoPedroAS51** [comment]
@francoism90 Thanks for report. I'll update the docs :)

**Pull request merged**
