### PR TITLE
feat(model): apply instances of relationships to nested objects

### LINKED ISSUE #74: Transforming Relations to their models
Thanks for the nice package!
Is there any way to change convert relations object to their model type!
for example, comment has many replies but when we including replies it is just giving comment as model and replies are still plain objects which in fact they should transform to their models! 
Screenshot from 2019-06-13 15-14-14

### PR DESCRIPTION
**Pull request by JoaoPedroAS51**
Hi!

This PR will extract the code of `find` and `get` that applies the response data in the current instance to two methods: `_applyInstance` and `_applyInstanceCollection`. It will also add two more methods: `relations` that contains an object of the relations and `_applyRelations` that is used in `construct` to apply the instance of the relationship in the nested objects, based on `relations` value.

This code was based on @Dylan-Chapman code. See https://github.com/robsontenorio/vue-api-query/issues/74#issuecomment-502492899

Closes #74 

### Usage:
You can apply a model instance to a nested object by setting the key and the model in `relations` method.

If the backend responds with:

```js
// response from API for /posts/1
{
  title: 'My title'
  body: 'Some text here',
  user: {
    firstName: 'John',
    lastName: 'Doe'
  }
}
```

We just need to set `user` to User model:

**/models/Post.js**
```js
class Post extends Model {
  relations () {
    return {
      // Apply User model to `user` object
      user: User
    }
  }
}
```

It also works for collections. So if the backend responds with:

```js
// response from API for /comments
{
  text: 'Some text here',
  user: {
    firstName: 'John',
    lastName: 'Doe'
  },
  replies: [
    {
      text: 'A reply here',
      user: {
        firstName: 'Joe',
        lastName: 'Doe'
      }
    },
    {
      text: 'Another reply here',
      user: {
        firstName: 'Mary',
        lastName: 'Doe'
      },
      replies: [
        {
          text: 'Yes, this is the reply of the reply!',
          user: {
            firstName: 'Max',
            lastName: 'Doe'
          }
        }
      ]
    }
  ]
}
```

Then we just need to set `user` to User model and `replies` to Comment model:

**/models/Comment.js**
```js
class Comment extends Model {
  relations () {
    return {
      // Apply User model to `user` object
      user: User,
      // Apply Comment model to each object of `replies` array
      replies: Comment
    }
  }
}
```

### CODE REVIEW

**Comment by robsontenorio** [comment]
Thanks for PR! Any breaking changes? Could you, please, update README with some relevant feature usage?

**Comment by JoaoPedroAS51** [comment]
@robsontenorio Eae cara, acabei de ver q vc é brasileiro também! Não tem nenhum breaking change. Claro, posso atualizar o README :)

**Comment by JoaoPedroAS51** [comment]
@robsontenorio Done https://github.com/robsontenorio/vue-api-query/pull/125/commits/5ba1a4466d1bb428662de737d781d8d6397ad8f8

**Review by Peter-Krebs — APPROVED** [review]
Nice adaption of the concept by @Dylan-Chapman - thank you, @JoaoPedroAS51

**Comment by JoaoPedroAS51** [comment]
Hi @Peter-Krebs! Thank you! :)

I just pushed an improvement to apply relations directly on construct, right after assign the attributes. See https://github.com/robsontenorio/vue-api-query/pull/125/commits/e676162066a88db926da0cea87303bf4f0be1d0f

This way if we create a new instance with data, the relations will be applied.
```js
const post = new Post({
  title: 'Something',
  text: 'Some text here',
  user: {
    firstName: 'John',
    lastName: 'Doe'
  }
})

post.user.fullName // it works because now the instance is applied on construct!
```

**Comment by robsontenorio** [comment]
@JoaoPedroAS51 Ficou ótimo! Obrigado pela contribuição ;) Lembrei do seu nome lá do `nuxt-auth`. No passado eu começei o trabalho do auto-refresh, mas o repo estava meio largado. Mas agora vai!

**Comment by francoism90** [comment]
Thanks for this PR! :)

Does it also work when using nested keys, e.g. `relationships.tags` instead of `tags`?

**Comment by JoaoPedroAS51** [comment]
Hi @francoism90! It currently doesn't work with nested keys, but I can make this improvement! :)

**Comment by JoaoPedroAS51** [comment]
@francoism90 Done! #127

**Pull request merged**
