### PR TITLE
feat(builder): add support to nested filters

### LINKED ISSUE #81: Nested filters
The JSON Api spec supports nested filters as far as I'm aware:
`?filter[invoices][deadline]`

It would be nice if there was some sort of a clean support for it. The only way to achieve this for me was using params atm:

```javascript
params: {
          "filter[invoices][deadline]": null,
          "filter[invoices][state]": null
 }
//....
Model.params(params);
```

Anyway I think that passing an object to the filter function should add the params recursively

### PR DESCRIPTION
**Pull request by JoaoPedroAS51**
Add support to nested filters to `where` and `whereIn`.

Closes #81 

### TODO
- [x] Update documentation of `where` and `whereIn`

### Usage

```js
await Model.where(['user', 'status'], 'active').get()
// GET /resource?filter[user][status]=active

await Model.whereIn(['user', 'status'], ['active', 'inactive']).get()
// GET /resource?filter[user][status]=active,inactive
```

### CODE REVIEW

**Comment by Peter-Krebs** [comment]
That's a good step forward, thanks!

Only problem I can see is the lack of CRUD, which I like to implement for anything.  
Currently, you would not be able to add or remove values for a key, only overwrite them, correct? It's not strictly neccessary but worth thinking about, you know someone is going to request that sooner or later.

**Comment by JoaoPedroAS51** [comment]
@Peter-Krebs I'm afraid I didn't understand. Can you open a new issue for this, so we could discuss more about it?

**Comment by JoaoPedroAS51** [comment]
@Peter-Krebs This PR is only related to nested filters support. Any other improvement will be handle in a new PR.

**Comment by Peter-Krebs** [comment]
@JoaoPedroAS51 Yes I'm talking about the filters.  

Consider this call:
`await Model.whereIn(['user', 'status'], ['active', 'inactive'])`

It would be nice to modify filters as well instead of just replacing the whole value.  
But I'm fine with your current solution, I just wanted to hear what you think about it.

**Comment by JoaoPedroAS51** [comment]
@Peter-Krebs I'm afraid that making such change would break the current structure we are following in this package, which I believe was inspired by Laravel’s Eloquent.

Maybe you could provide an usage example where adding and removing filters would be useful. That way we can think together in a solution :)

I recommend opening a new issue to discuss about this, because such change is outside the scope of this PR.

What do you think @robsontenorio?

**Comment by robsontenorio** [comment]
I think we can get started with the simple solution.

**Review by robsontenorio — APPROVED** [review]

**Comment by dionysiosarvanitis** [comment]
Seems like solution does not support two nested values or am I doing something wrong?  

```js
query.where(['schedule', 'start'], start)
    .where(['schedule', 'end'], end)
`

**Comment by JoaoPedroAS51** [comment]
Hi @dionysiosarvanitis! Thank you for your report. I'm working on a fix for your issue :)

**Comment by JoaoPedroAS51** [comment]
@dionysiosarvanitis Done #154 :wink:

**Comment by dionysiosarvanitis** [comment]
@JoaoPedroAS51 that was really quick! Thank you!

**Pull request merged**
