### PR TITLE
Closes #40

### LINKED ISSUE #40: Missing fromResource of nested models
I have nested models like 
User -> hasMany -> Posts.

When I try to fetch my post record like following:
```
let user = await User.find(1)
let post = await user.posts().find(myId)
```
my `post` will not have `_fromResource` property present, therefore it's not possible to update it using `save()` function, while if to use `get()` property is present and its possible to update record. Was it done intentionally or just a bug? For reference:

`find()` - https://github.com/robsontenorio/vue-api-query/blob/master/src/Model.js#L208
`get()` - https://github.com/robsontenorio/vue-api-query/blob/master/src/Model.js#L219

### PR DESCRIPTION
**Pull request by taai**
I had the same issue (Missing fromResource on nested relations while using find()), so I just dag in the code and found a solution.

### CODE REVIEW

**Comment by robsontenorio** [comment]
@taai  Please, could you commit on PR the missing test case related to this issue?

**Comment by robsontenorio** [comment]
@taai this issue #40  has opened dec/2018. Can you reproduce it on latest version 1.5.1?

**Comment by saschametz** [comment]
I'm using the current version and I have the same issue

**Comment by taai** [comment]
@robsontenorio Today I had time to spare, so I wrote the test. The test case is this:

```JavaScript
const post = new Post({ id: 1 })
const comment = await post.comments().find(1)
comment.text = 'Hola!'
await comment.save()
```

Without my patch ```comment.save()``` makes a PUT request to ```/comments/1```, but it should make a PUT request to ```/posts/1/comments/1```. The problem is that ```comment._fromResource``` is ```undefined``` and my patch solves it.

**Comment by taai** [comment]
@robsontenorio Oh, I didn't answer your question. Yes, this issue was in v1.5 when I wrote my patch and still is in newest v1.5.1.

**Comment by robsontenorio** [comment]
@taai Just noticed your commig message 

"If you don't use "await" for function that returns Promise, the test will actually pass. Multiple other tests did not "await". "

What do you exactly mean? With promisse or "await" the tests must have same behavior.

**Pull request closed without merging**
